[workspace]
members = [
  "contracts/*",
]
resolver = "2"

[workspace.dependencies]
soroban-sdk = {version = "20.0.2"}
soroban-token-sdk = {version = "20.0.2"}

[profile.release]
codegen-units = 1
debug = 0
debug-assertions = false
lto = true
opt-level = "z"
overflow-checks = true
panic = "abort"
strip = "symbols"

[profile.release-with-logs]
debug-assertions = true
inherits = "release"
